services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - CLOUDFLARE_ZONE_ID=${CLOUDFLARE_ZONE_ID}
      - DOMAIN="example.com"
      - DNS_PROVIDER="cloudflare"
      - DNS_ENTRIES_TO_SYNC="*.dev,dev"
    networks:
      - services

networks:
  services:
    driver: bridge