apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}