name: Continuous Integration Workflow

on:
  push:
    branches: [ 'main' , "feature/*" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v7
          - linux/arm64

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV        

      - name: Log configuration
        run: |
          echo "Registry: ${{ env.REGISTRY }}"
          echo "Repository: ${{ github.repository }}"
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.ACTIONS_TOKEN }}

      - name: Get the version
        id: packageversion
        run: |
          echo "Setting version to $(cat package.json | jq -r .version)"
          echo "VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "dynamic-dns") | .version')" >> "$GITHUB_OUTPUT"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ env.REGISTRY }}/${{ github.repository }}"
          tags: |
            type=semver,pattern={{version}}
            type=sha
            type=sha,format=long
            type=raw,value=${{ steps.packageversion.outputs.VERSION }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

