name: Continuous Integration Workflow

on:
  push:
    branches: [ 'main' ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log configuration
        run: |
          echo "Registry: ${{ env.REGISTRY }}"
          echo "Repository: ${{ github.repository }}"

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.ACTIONS_TOKEN }}

      - name: Get the version
        id: packageversion
        run: |
          echo "Setting version to $(cat package.json | jq -r .version)"
          echo "VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "dynamic-dns") | .version')" >> "$GITHUB_OUTPUT"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ env.REGISTRY }}/${{ github.repository }}"
          tags: |
            type=semver,pattern={{version}}
            type=sha
            type=sha,format=long
            type=raw,value=${{ steps.packageversion.outputs.VERSION }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Trigger CD workflow
        run: |
          echo "Triggering CD workflow"
          echo "Registry: ${{ env.REGISTRY }}"
          echo "Repository: ${{ github.repository }}"
          echo "Tags: ${{ steps.packageversion.outputs.VERSION }}"
          
          export FULL_URL="https://api.github.com/repos/${{ github.repository }}/actions/workflows/cd.yaml/dispatches"
          
          echo "Full URL: $FULL_URL"
          
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.ACTIONS_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            $FULL_URL \
            -d '{
            "ref":"main",
            "inputs": {
              "image_registry": "${{ env.REGISTRY }}",
              "image_repository": "${{ github.repository }}",
              "image_tag": "${{ steps.packageversion.outputs.VERSION }}"
              }
            }'
